Fix unhandled exception removing deep missing path
e.g. trying to remove the value at path: /missing1/missing2

Before:
NoMethodError: undefined method 'key?' for nil:NilClass

After:
Hana::Patch::IndexError